// Code generated by stst; DO NOT EDIT.
package models

var DemoQuery = `
SELECT
    bigint_col,
    text_col
FROM
    basic_types
LIMIT 10;`

type Demo struct {
	BigintCol int64
	TextCol   string
}

func (x *Demo) GetScanDests() []interface{} {
	return []interface{}{&x.BigintCol, &x.TextCol}
}
