// Code generated by stst; DO NOT EDIT.
package models

import "time"

var HardworkingStaffQuery = `
SELECT
    staff.staff_id,
    staff.first_name,
    staff.last_name,
    date_trunc('month', payment.payment_date) AS payment_month,
    sum(payment.amount) AS amount
FROM
    staff,
    payment
WHERE
    staff.staff_id = payment.staff_id
GROUP BY
    staff.staff_id,
    staff.first_name,
    staff.last_name,
    date_trunc('month', payment.payment_date)
LIMIT 10;`

type HardworkingStaff struct {
	StaffId      int32     `boil:"staff_id"`
	FirstName    string    `boil:"first_name"`
	LastName     string    `boil:"last_name"`
	PaymentMonth time.Time `boil:"payment_month"`
	Amount       float64   `boil:"amount"`
}

func (x *HardworkingStaff) GetScanDests() []interface{} {
	return []interface{}{&x.StaffId, &x.FirstName, &x.LastName, &x.PaymentMonth, &x.Amount}
}
