name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: |
          docker run -ti --rm -p 15432:5432 -e POSTGRES_PASSWORD=postgres postgres:11
      - run: go test -v
